### PR TITLE
Add TextChanged action for peeking

### PR DESCRIPTION
**Pull request by garyb**
Unfortunately this means specialising `g` to `Aff` rather than being able to just use the `MonadEff` constraint, as there's now a usage of `aff-coroutines` so we can subscribe to changes from the component.

Also updated the build for pursuit publishing, tweaked some formatting for consistency.

### CODE REVIEW

**Comment by jonsterling** [comment]
:+1:

**Comment by garyb** [comment]
Thanks!

**Comment by jdegoes** [comment]
Can't you use `MonadAff` here?

**Comment by jdegoes** [comment]
Actually, why can't `aff-coroutines` use `MonadAff`, too?

**Comment by garyb** [comment]
If `aff-coroutines` can be updated to use `MonadAff` then yeah, we can too. It calls `runAff` internally though, so I'm not sure if there's a way to do it based on the way it is now.

**Comment by garyb** [comment]
https://github.com/paf31/purescript-aff-coroutines/blob/63b015ef645105aef67fb4ca5b6d1878e928605c/src/Control/Coroutine/Aff.purs#L35-L39

**Comment by garyb** [comment]
Okay, yeah it can be :smile: I'll make a PR

**Pull request merged**
