### PR TITLE
Update for new Halogen, use lifecycle component

### PR DESCRIPTION
**Pull request by garyb**

### CODE REVIEW

**Comment by garyb** [comment]
@cryogenian could you review this please? I reverted to the pre-finalizer-hack and then made updates for Halogen 0.6, so I'm not sure if there was anything that we added during the finalizer hack that also needs keeping.

**Comment by cryogenian** [comment]
This looks awesome! 
I'm a bit confused with `ref`s and `initializer`, though. `ref` handler with `Just` input runs before `initializer`, right? What if we have something like?

``` purescript
HH.div_
  if state.foo then [] else [ HH.p [ P.ref (\el -> action SetEl) ] [ H.text "Bar" ] ] 
```

When does `initializer/finalizer` run in this case?

**Comment by garyb** [comment]
`initializer` and `finalizer` are linked to when the component appears in the tree, not to when the HTML is rendered. That's why we have to check whether we have a `Just el` in the state when the `initializer` runs: https://github.com/slamdata/purescript-ace-halogen/pull/13/files#diff-8dc47c60a59c3e7230c8e1d03dfc6002R193

`ref` is still a bit of a hack really, it can only safely be used like we have it here: saving an element reference that is then picked up by the `initializer`. What the new ref/initializer/finalizer setup gives us though is that if you save an element with `ref`, then do something with it in `initializer`, you're guaranteed that the element is in the DOM.

`ref` will fire with `Nothing` if the element it's attached to is removed within the component, but it won't fire if the entire component is removed, whereas the `finalizer` will. So there may be some cases where it still is useful to run `ref`, but you'd probably want to run the same actions in a `finalizer` that are also triggered by a `SetElement Nothing`.

Anyway... for the case we have here, none of that matters :smile: as we have constant HTML for the component so the behaviour of it is totally predictable.

There's a probably better explanation of the lifecycle stuff here: https://github.com/slamdata/purescript-halogen/blob/v0.6.1/GUIDE.md#component-lifecycles

**Comment by cryogenian** [comment]
Yeah, I've read this. That's why I've asked about non-constant element and initializers :) 
:+1: for this pr

**Comment by garyb** [comment]
Yeah, I'm not sure I'd trust using non-constant HTML with `ref` until we experiment with it a bit more, but I don't think we'll be using that anywhere anyway, currently.

The fact that `initializer` is now not dependant on a HTML reference will also be nicer in a bunch of places for us, where we do the `BrowserFeatures` stuff, etc. which has nothing to do with the DOM but is something effectful we want to initialize with the component.

Thanks for reviewing!

**Pull request merged**
